### PR TITLE
Added KissAnime Streaming site

### PR DESCRIPTION
**Pull request by rosaage**
I added support for the streaming site kissanime.to

### CODE REVIEW

**Comment by Diablofan** [comment]
This will get rejected as KissAnime is not an official site and is clearly
stated in the FAQ and wiki that such patches will be rejected.

**Comment by erengy** [comment]
Sorry, but I can't accept this. Please see #75, #155, #184 and #254 for more information.

**Comment by rosaage** [comment]
I am sorry, I did not read the faq. I have removed the fork from my github page.

**Comment by erengy** [comment]
No problem. It's generally a good idea to at least [search the issues](https://github.com/erengy/taiga/issues?utf8=%E2%9C%93&q=is%3Aissue+kissanime) for previous discussions, though.

**Pull request closed without merging**
