### PR TITLE
anime_relations: Add Under the Dog

### PR DESCRIPTION
**Pull request by wiiaboo**
DameDesuYo called it episode 00 for some reason.

### CODE REVIEW

**Comment by wopian** [comment]
Because that's what the studio is calling the episode. http://under-the-dog.com/

**Comment by wiiaboo** [comment]
That still doesn't make much sense. It implies there's going to be a series after.

**Comment by wopian** [comment]
Well it being a series was the [original intention](https://en.wikipedia.org/wiki/Under_the_Dog?wprov=sfla1), hopefully we may see this one day if this revival OVA proves to be a success.

**Comment by erengy** [comment]
Hey @wiiaboo. I've moved anime relations to a [separate repository](https://github.com/erengy/anime-relations) now. Could you send another PR there? Please also make sure to place the rule alphabetically and update the `last_modified` date. Thanks.

**Pull request closed without merging**
