### PR TITLE
setup/Taiga.nsi: create desktop shortcut disableable by user

### PR DESCRIPTION
**Pull request by wiiaboo**

### CODE REVIEW

**Comment by erengy** [comment]
Hi @wiiaboo,

This is a bit hacky, so I looked into adding a components page to the installer:

components

What do you think? This seems like a better solution to me, allowing for more options.

**Comment by tophf** [comment]
The installer option method is the widely (and wisely) used one.

**Comment by wiiaboo** [comment]
If it could save the component selection across updates it'd be great too, but not essential.

**Comment by wiiaboo** [comment]
Fullfilled in https://github.com/erengy/taiga/commit/213d555f63fb2cc9cd01a25e5fbcdbdbe2da85fa

**Pull request closed without merging**
