### PR TITLE
Add shortcut Ctrl+K for opening anime folder

### PR DESCRIPTION
**Pull request by sunjayc**
Adds a keyboard shortcut for opening the currently selected anime item's folder.

### CODE REVIEW

**Comment by erengy** [comment]
Was <kbd>Ctrl</kbd>+<kbd>K</kbd> a random choice, or does it replicate a well-known behavior that I'm not aware of?

Why not <kbd>Ctrl</kbd>+<kbd>O</kbd> for "Open", for instance?

Also, you need to `return TRUE;` as in all other key handlers around, which will tell the OS that no further processing is necessary.

**Comment by sunjayc** [comment]
Random choice. I didn't do Ctrl+O because that's usually associated with opening a file in the current application, not opening an external file.

**Comment by erengy** [comment]
While you're right, I still think that <kbd>Ctrl</kbd>+<kbd>O</kbd> would be more intuitive. Merging this PR now, but I'll give it some thought and probably change the shortcut.

**Comment by wopian** [comment]
<kbd>Ctrl</kbd>+<kbd>E</kbd>. 

Keeps behavior consistent with windows' existing shortcuts - <kbd>Win</kbd>+<kbd>E</kbd> opens an explorer window.

**Pull request merged**
