### PR TITLE
Update Jellyfin Integration

### PR DESCRIPTION
**Pull request by juplayLP**
The current Version of the Jellyfin integration had an erroneous ! in the Regex, which has been removed in this PR. Also allow finding it, in the same way as Plex is detected, via IP.

### CODE REVIEW

**Comment by erengy** [comment]
Hey @juplayLP, thanks for the PR.

After seeing today's conversation at the Discord server, I installed the latest version of Jellyfin and the URL was in `/web/index.html#!/video` format. In other words, the default configuration seems to have `#!`, as you mentioned.

If the `!` is optional, maybe we should make it so (i.e. `#!?/video`). We could also add another case for subdomains, if required. Would you like to update the PR accordingly?

**Comment by erengy** [comment]
Simplifying the entire regex to `/web/index.html#!/video` might just work too, as @redeven suggested. Would that cause any issues with Plex detection?

**Comment by juplayLP** [comment]
> Simplifying the entire regex to /web/index.html#!/video might just work too, as @redeven suggested. Would that cause any issues with Plex detection?

Can confirm that it does work, but i would probably put the `index.html` there as not strictly needed, as with the default nginx config given by the jellyfin project [here](https://jellyfin.org/docs/general/networking/nginx), there is a location block in there that points /web/ to /web/index.html, to make it work as `domain.tld/web/#!/video` for the video playback

**Comment by juplayLP** [comment]
forgot to add that it shouldn't affect plex detection, as you worked with full domain coverage there, while this one tries to be as generic yet specific to jellyfin as possible.

**Comment by juplayLP** [comment]
forgot to add that it shouldn't affect plex detection, as you worked with full domain coverage there, while this one tries to be as generic yet specific to jellyfin as possible. But I don't have plex installed, and didn't really plan to do that again, so as always, no guarantees 😅

**Comment by erengy** [comment]
Thanks. So the pattern becomes `/web/(?:index\\.html)?#!/video` then, making `index.html` optional. If that's correct, I can merge the PR with that.

**Comment by juplayLP** [comment]
@erengy have tested all ways I know how to access Jellyfin with your pattern above (see the description/comment in 05a5b8abccee0be309c30c442a1ae1f86a88dd93 for which forms of access i tested) successfully.
should be ready to merge now, once the check there runs through

**Pull request merged**
